### PR TITLE
Merge feature/working-branch into development branch

### PR DESCRIPTION
**Pull request by Joseph-Burke**
The authors request to merge the feature/working-branch into the development branch now that the following work has been completed:

1. All 14 requirements of the assignment have been met and tested.
2. A descriptive README.md file has been written to explain the project.
3. Errors thrown by the rubocop linter have been corrected.

### CODE REVIEW

**Comment by lekegitrepo** [comment]
#### Hi @Joseph-Burke and @Alaska01 :clap: :clap:
#### You have done a good job so far. However, some test cases are still failing. Check my comments below.

**_1. The `multiply_els` should be defined outside of the enumerable module._**

**_2. `my_all?`:_**
**_`[2, 1, 6, 7, 4, 8, 10].my_all?(3) # => false`_**
**_`%w[Marc Luc Jean].my_all?('Jean') # => false`_**
**_`%w[Marc Luc Jean].my_all?(/a/) # => false`_**

**_3. `my_any?`:_**
**_`%w[Marc Luc Jean].my_any?(/d/) # => false`_**
**_`[2, 1, 6, 7, 4, 8, 10].my_any?(7) # => true`_**
**_`%w[Marc Luc Jean].my_any?('Jean') # => true`_**
**_`[nil, true, 99].my_any?(Integer) # => true`_**
**_`['1', 5i, 5.67].my_any?(Numeric) # => true`_**

**_4. `my_none?`:_**
**_`%w[Marc Luc Jean].my_none?(/j/) #=> true`_**
**_`[2, 1, 6, 7, 4, 8, 10].my_none?(15) #=> true`_**
**_`%w[Marc Luc Jean].my_none?('Jean')`_**
**_`[1, 3.14, 42].my_none?(Float)`_**
**_`[1, 5i, 5.67].my_none?(Numeric)`_**

**_Fix these and submit for review_**

#### _Reviewed by Temitayo Adeleke._

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
#### Status: Request changes

**Comment by Joseph-Burke** [comment]
**Changes requested by @lekegitrepo have been implemented.**

> **_1. The `multiply_els` should be defined outside of the enumerable module._**

> **_2. `my_all?`:_**
> **_`[2, 1, 6, 7, 4, 8, 10].my_all?(3) # => false`_**
> **_`%w[Marc Luc Jean].my_all?('Jean') # => false`_**
> **_`%w[Marc Luc Jean].my_all?(/a/) # => false`_**

> **_3. `my_any?`:_**
> **_`%w[Marc Luc Jean].my_any?(/d/) # => false`_**
> **_`[2, 1, 6, 7, 4, 8, 10].my_any?(7) # => true`_**
> **_`%w[Marc Luc Jean].my_any?('Jean') # => true`_**
> **_`[nil, true, 99].my_any?(Integer) # => true`_**
> **_`['1', 5i, 5.67].my_any?(Numeric) # => true`_**

> **_4. `my_none?`:_**
> **_`%w[Marc Luc Jean].my_none?(/j/) #=> true`_**
> **_`[2, 1, 6, 7, 4, 8, 10].my_none?(15) #=> true`_**
> **_`%w[Marc Luc Jean].my_none?('Jean')`_**
> **_`[1, 3.14, 42].my_none?(Float)`_**
> **_`[1, 5i, 5.67].my_none?(Numeric)`_**

tests-screenshot

**Comment by lekegitrepo** [comment]
#### Hi @Joseph-Burke and @Alaska01 :clap:  :clap:
#### You have done a great job, but there are two test cases that are returning false instead of true. Check my comment below.

- **_These should return true:_**
**_`[1, 5i, 5.67].my_all?(Numeric) # => true`_**
**_`[2, 1, 6, 7, 4, 8, 10].my_all?(Integer) # => true`_**

#### _Reviewed by Temitayo Adeleke_.

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
#### Status: Request changes

**Comment by Joseph-Burke** [comment]
**Further changes on #my_all? have now been implemented.**

> * **_These should return true:_**
>   **_`[1, 5i, 5.67].my_all?(Numeric) # => true`_**
>   **_`[2, 1, 6, 7, 4, 8, 10].my_all?(Integer) # => true`_**

tests-screenshot-2

**Comment by lekegitrepo** [comment]
> **Further changes on #my_all? have now been implemented.**
> 
> > * **_These should return true:_**
> >   **_`[1, 5i, 5.67].my_all?(Numeric) # => true`_**
> >   **_`[2, 1, 6, 7, 4, 8, 10].my_all?(Integer) # => true`_**
> 
> <img alt="tests-screenshot-2" width="1183" src="https://user-images.githubusercontent.com/56026099/88464195-b7b6d500-ceb0-11ea-9595-0404420e9ff5.

**Comment by lekegitrepo** [comment]
#### Hi @Joseph-Burke and @Alaska01 
#### Well done. It seems that when you implement required changes another part of the code breaks. I will list below all the test cases for my_all method.

**_my_all tests cases:_**
- **_%w[Marc Luc Jean].my_all? { |text| text.size >= 3 }) # => true_**
- **_`%w[Marc Luc Jean].my_all? { |text| text.size >= 4 }) # => false`_**
- **_`[2, 1, 6, 7, 4, 8, 10].my_all?(3) # => false`_**
- **_`%w[Marc Luc Jean].my_all?('Jean') # => false`_**
- **_`%w[Marc Luc Jean].my_all?(/a/) # => false`_**
- **_`[1, 5i, 5.67].my_all?(Numeric) # => true`_**
- **_`[2, 1, 6, 7, 4, 8, 10].my_all?(Integer) # => true`_**
- **_[nil, true, 99].my_all? # => false_**
- **_`[nil, false].my_all? # => false`_**
- **_`[nil, nil, nil].my_all? # => false`_**
- **_`[].my_all? # => true`_**

**_feel free to contact me on slack if you have doubt or questions_**

#### _Reviewed by Temitayo Adeleke_

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
#### Status: Request changes

**Comment by Joseph-Burke** [comment]
@lekegitrepo Thanks for another review - we're nearly there!

There was a silly mistake I overlooked in the code for #my_all? where 'if' was used instead of 'unless'. Now that that's been corrected, all the tests for #my_all? are returning the correct values.

Screenshot 2020-07-26 at 11 14 04

**Review by rOluochKe — APPROVED** [review]
Hello Team!
### You finally got it right, well done :clap: The project has been approved. Congratulations :boom: :100:
### Merge and submit the project. Good luck with the next one.
- Happy coding!

**Pull request merged**
